theme: jekyll-theme-minimal
title: CrazyHman Gaming Site
description: Starting a gaming blog to keep records of the games I played over the years.
avatar: <img src="images/piggy.jpg">
footer-links: 
facebook:
twitter: @Hpk115
youtube:

