theme: jekyll-theme-minimal
title: CrazyHman Gaming Blog
description: Starting a gaming blog to keep records of the games I played over the years.

- Battlefield 1
- Detroit Become Human
- Kingdom Hearts Re:Chain of Memories
